# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ task4 ]
  pull_request:
    branches: [ task4 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cd task4
        mkdir 3rdparty
        cd 3rdparty
        git clone https://github.com/google/googletest
        export GOOGLE_TEST_DIR=googletest
        cmake -DCMAKE_INSTALL_PREFIX=/home/runner/work/tp_homework/tp_homework/task4 ..
        make
        make install
    
    - name: UploadArtifacts
      uses: actions/upload-artifact@v1
      with: 
        name: Distributive
        path: /home/runner/work/tp_homework/tp_homework/task4/exe      
      
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path: "bin/CTestExe"
        report-path: "report.xml"
        working-directory: "task4"

